
-- KHAI BÁO BIẾN
DECLARE @MASV CHAR(10), @HOTEN VARCHAR(30), @NGAYSINH DATE
-- GÁN GIÁ TRỊ CHO BIẾN
	-- CÁCH 1 DÙNG LỆNH SET
SET @MASV = '2001215640'
SET @HOTEN = 'Dinh Thi Tuyet Chinh'
SET DATEFORMAT DMY
SET @NGAYSINH = '20/04/2003'

-- GÁN GIÁ TRỊ CỦA BIỂU THỨC CHO BIẾN
DECLARE @DIEMTOAN DECIMAL(3,1), @DIEMLI DECIMAL(3,1), @DIEMTB DECIMAL (3, 1)
SET @DIEMTOAN = 7
SET @DIEMLI = 8
SET @DIEMTB = (@DIEMTOAN + @DIEMLI) / 2

-- GÁN CÂU TRUY VẤN CHO BIẾN
DECLARE @TONGSV INT
SET @TONGSV = (SELECT COUNT(MASV)
				FROM SINHVIEN
				WHERE MALOP = '10DHSH1')

-- GÁN GIÁ TRỊ CHO BIẾN
	-- CÁCH 2 DÙNG LỆNH SELECT
