-- Tạo một thủ tục có tên là XINCHAOTG và in ra câu 'HELLO WORLD'
-- TẠO THỦ TỤC
CREATE PROCEDURE XINCHAOTG
AS
	PRINT 'HELLO WORLD'
-- THỰC THI THỦ TỤC
EXEC XINCHAOTG
-- XOÁ THỦ TỤC
DROP PROC XINCHAOTG


-- Thủ tục nhập vào họ tên và in ra câu 'Xin chào ' + họ tên được nhập vào

CREATE PROCEDURE XINCHAO
@HOTEN NVARCHAR(40), @LOP NVARCHAR(30)
AS
	BEGIN
	PRINT N'XIN CHÀO ' +@HOTEN + ' '+@LOP
	END
GO

EXEC XINCHAO @HOTEN = N'Đinh Thị Tuyết Chinh', @LOP = '12DHTH13'
	-- THAY ĐỔI NỘI DUNG THỦ TỤC
ALTER PROC XINCHAO
@HOTEN NVARCHAR(40), @LOP NVARCHAR(30)
AS
	BEGIN
	PRINT N'Chào ' +@HOTEN + ' '+@LOP
	END
GO

EXEC XINCHAO @HOTEN = N'Đinh Thị Tuyết Chinh', @LOP = '12DHTH13'
	-- Ví dụ tham số đầu vào
CREATE PROC CONG @a INT, @b INT
AS
	PRINT @a + @b
GO

EXEC CONG @a = 3, @b = 2

	CREATE PROC DSLOP @MALOP CHAR(10)
	AS
		SELECT *
		FROM SINHVIEN
		WHERE MALOP = @MALOP
	GO


	CREATE PROC TT_SV @MASV CHAR(10) = 'SV001'
	AS
		SELECT *
		FROM SINHVIEN
		WHERE MASV = @MASV
	GO

	EXEC TT_SV

--- Mã hoá thủ tục
CREATE PROC ENCRYTION_MASV
@MASV CHAR
WITH ENCRYPTION
AS
	BEGIN
		SELECT *
		FROM SINHVIEN
		WHERE MASV = @MASV
	END
GO
sp_HelpText ENCRYTION_MASV



EXEC ENCRYTION_MASV @MASV = 'SV002'

	SELECT * FROM SINHVIEN