CREATE DATABASE DB_QLHV

ON PRIMARY
(
	NAME = 'DBQLHV_PRIMARY',
	FILENAME = 'D:\DBQLHV_PRIMARY.mdf',
	SIZE = 5MB,
	MAXSIZE = 10MB,
	FILEGROWTH = 10%
)
LOG ON
(
	NAME = 'DBQLHV_LOG',
	FILENAME = 'D:\DBQLHV_LOG.ldf',
	SIZE = 3MB,
	MAXSIZE = 5MB,
	FILEGROWTH = 15%
)

CREATE TABLE LOPHOC
(
	MALOP CHAR(10),
	SISO INT, 
	LOPTRUONG CHAR(10),
	GVQUANLI CHAR(10),
	NAMBATDAU INT,
	NAMKETTHUC INT,
	 CONSTRAINT PK_LOPHOC PRIMARY KEY(MALOP)
)

CREATE TABLE HOCVIEN
(
 MAHOCVIEN CHAR(10) NOT NULL,
 TENHOCVIEN NVARCHAR (50),
 NGAYSINH DATE,
 TINHTRANG NVARCHAR(30),
 MALOP CHAR(10),
 CONSTRAINT PK_HOCVIEN PRIMARY KEY(MAHOCVIEN),
 CONSTRAINT FK_HV_LOP FOREIGN KEY (MALOP) REFERENCES LOPHOC(MALOP)
)

CREATE TABLE GIAOVIEN
(
 MAGV CHAR(10) NOT NULL,
 TENGV NVARCHAR (50),
 NGAYSINH DATE,
 GIOITINH NVARCHAR(10),
 DIENTHOAI CHAR(30),
 MAGVQUANLI CHAR(10),
 CONSTRAINT PK_GV PRIMARY KEY(MAGV),
 CONSTRAINT FK_GV_LOP FOREIGN KEY (MAGVQUANLI) REFERENCES LOPHOC(GVQUANLI)
)

CREATE TABLE MONHOC
(
	MAMONHOC CHAR(10),
	TENMONHOC NVARCHAR(50),
	SOCHI INT,
	CONSTRAINT PK_MH PRIMARY KEY (MAMONHOC)
)

CREATE TABLE KETQUA
(
 MAHOCVIEN CHAR(10) NOT NULL,
 MAMONHOC CHAR(10) NOT NULL,
 LANTHI INT, 
 DIEM FLOAT,

 )
